"""French paraphrase catalog for TRACER bootstrap (Phase B').

Semantics align with tracer_data/EMOTIONS_REFERENCE.md.
"""

from __future__ import annotations

from typing import Final


def _emotion(intent: str) -> str:
    return f"play_emotion:{intent}"


def _dedupe(phrases: list[str]) -> list[str]:
    seen: set[str] = set()
    out: list[str] = []
    for phrase in phrases:
        key = phrase.strip()
        if key and key not in seen:
            seen.add(key)
            out.append(key)
    return out



# Minimum counts enforced by tests

_HEAD_ON: Final[list[str]] = _dedupe(
    [
        "Regarde-moi.",
        "Regarde moi.",
        "Regarde moi!",
        "Regarde-moi!",
        "Regarde moi s'il te plaît.",
        "Regarde-moi s'il te plaît.",
        "Suis-moi des yeux.",
        "Fixe-moi.",
        "Garde un œil sur moi.",
        "Tourne-toi vers moi.",
        "Tu peux me suivre du regard?",
        "Tu peux me regarder?",
        "Quand je te parle, tu me regardes.",
        "Regardez quand je te parle!",
        "Je veux que tu me regardes.",
        "Regarde-moi dans les yeux.",
        "Suis mon regard.",
        "Accroche ton regard sur moi.",
        "Mets ton regard sur moi.",
        "Porte ton regard sur moi.",
        "Observe-moi.",
        "Reste concentré sur moi.",
        "Ne lâche pas mon regard.",
        "Garde les yeux sur moi.",
        "Suis-moi du regard.",
        "Orienter tes yeux vers moi.",
        "Oriente tes yeux vers moi.",
        "Regarde moi bien.",
        "Regarde moi maintenant.",
        "Regarde moi stp.",
        "Eh regarde moi.",
        "Hey regarde moi.",
        "Regarde moi là.",
        "Suis mes yeux.",
        "Fixe ton regard sur moi.",
        "Lâche pas mon regard.",
        "Reste sur moi avec les yeux.",
        "Track-moi.",
        "Suis-moi visuellement.",
        "Regarde moi Richie.",
        "Regarde-moi Archie.",
    ]
)

_HEAD_OFF: Final[list[str]] = _dedupe(
    [
        "Arrête de me regarder.",
        "Ne me regarde plus.",
        "Lâche-moi des yeux.",
        "Cesse de me suivre.",
        "Arrête de me suivre des yeux.",
        "Ne me fixe plus.",
        "Détourne le regard.",
        "Regarde ailleurs.",
        "Arrête le suivi.",
        "Ne me suis plus du regard.",
        "Laisse-moi tranquille avec ton regard.",
        "Tu peux arrêter de me regarder.",
        "Arrête le head tracking.",
        "Stop de me suivre.",
        "Je n'ai plus besoin que tu me regardes.",
        "Tu peux regarder ailleurs.",
        "Ne fixe plus mes yeux.",
        "Ça suffit de me regarder.",
        "Arrête de fixer.",
        "Cesse de fixer.",
        "Lâche mon regard.",
        "Ne track plus.",
        "Pas besoin que tu me suives.",
        "Relâche le suivi.",
        "Fini de me suivre.",
        "Coupe le suivi visuel.",
        "Arrête de track.",
        "Arrête de me fixer.",
        "Plus besoin de me suivre.",
        "Arrête le suivi des yeux.",
        "Désactive le suivi.",
        "Ne me regarde plus s'il te plaît.",
        "Enfin arrête de me fixer.",
        "Arrête ça de me suivre.",
        "Arrête de me suivre Richie.",
        "Stop le tracking.",
        "Tu peux lâcher mon regard.",
        "Désactive le regard.",
        "Arrête de me suivre du regard.",
        "Ne me suis plus.",
    ]
)

_STOP: Final[list[str]] = _dedupe(
    [
        "Stop.",
        "Arrête.",
        "Arrête-toi.",
        "Ça suffit.",
        "On se calme.",
        "Stop tout.",
        "Arrête tout.",
        "Stop danse.",
        "Arrête de danser.",
        "Arrête l'émotion.",
        "Stop les mouvements.",
        "On s'arrête là.",
        "Ok stop.",
        "Stop Richie.",
        "Arrête Richie.",
        "Stop maintenant.",
        "Arrête maintenant.",
        "Mets-toi à l'arrêt.",
        "Stop tout de suite.",
        "Arrête de bouger.",
        "Arrête de bouger stp.",
        "Ça suffit comme ça.",
        "Tu t'arrêtes.",
        "Arrête ça tout de suite.",
        "Stop ça.",
        "Arrête ce que tu fais.",
        "Coupe tout.",
        "Stoppe.",
        "Stoppe-toi.",
        "Arrête de bouger là.",
        "Arrête les gestes.",
        "Tout stop.",
        "Halte.",
        "Allez on arrête.",
        "Allez, on arrête, j'en ai marre.",
        "Arrête tout de suite.",
        "Stop les danses.",
        "Stop l'émotion.",
        "Ça va c'est bon.",
        "Plus besoin de bouger.",
    ]
)

_DANCE: Final[list[str]] = _dedupe(
    [
        "Danse.",
        "Danse!",
        "Vas-y danse.",
        "Montre-moi une danse.",
        "Bouge un peu.",
        "Fais une danse.",
        "Danse pour moi.",
        "Montre ta danse.",
        "Tu peux danser?",
        "Fais-moi une chorégraphie.",
        "Danse maintenant.",
        "Allez danse.",
        "Danse Richie.",
        "Danse un peu.",
        "Montre-moi tes pas.",
        "Vas-y bouge.",
        "Fais ta danse.",
        "Lance une danse.",
        "Démarre une danse.",
        "Commence à danser.",
        "Fais danser.",
        "Danse stp.",
        "Montre un peu de danse.",
        "Un peu de danse.",
        "Danse s'il te plaît.",
        "Fais de la danse.",
        "Bouge comme une danse.",
        "Montre-moi comment tu danses.",
        "Exécute une danse.",
        "Enchaîne une danse.",
        "Lance la danse.",
        "Active la danse.",
        "Fais bouger ton corps.",
        "Danse pour de vrai.",
        "Bouge sur de la musique.",
        "Bouge sur la musique.",
        "Mets-toi à danser.",
        "Lance une chorégraphie.",
        "Danse pour moi Richie.",
        "Montre une chorégraphie.",
    ]
)

_MOVE_LEFT: Final[list[str]] = _dedupe(
    [
        "Regarde à gauche.",
        "Tourne la tête à gauche.",
        "Orienter-toi à gauche.",
        "Oriente-toi à gauche.",
        "À gauche Richie.",
        "Tourne à gauche.",
        "Regarde vers la gauche.",
        "Bouge la tête à gauche.",
        "Le regard à gauche.",
        "Va à gauche avec la tête.",
        "Tourne ton regard à gauche.",
        "Regarde côté gauche.",
        "Tourne-toi vers la gauche.",
        "Oriente ton regard à gauche.",
        "Tête à gauche.",
        "Mets ta tête à gauche.",
        "Regarde du côté gauche.",
        "Tourne la tête vers la gauche.",
        "Fixe à gauche.",
        "Regarde à gauche stp.",
        "Hey à gauche.",
        "Regarde à gauche qui c'est.",
        "Regarde vers le côté gauche.",
        "Tourne à gauche la tête.",
        "Dirige ton regard à gauche.",
        "À gauche avec la tête.",
        "Déplace ta tête à gauche.",
        "Tourne la tête du côté gauche.",
        "Gauche avec la tête.",
        "Oriente-toi vers la gauche.",
        "Regarde le côté gauche.",
        "Tête vers la gauche.",
        "Tourne vers la gauche.",
        "Regarde à gauche maintenant.",
        "Tourne la tête sur la gauche.",
        "Dirige-toi à gauche.",
        "À gauche avec ton regard.",
        "Pose ton regard à gauche.",
        "Tourne à gauche s'il te plaît.",
        "Regarde à gauche là.",
    ]
)

_MOVE_RIGHT: Final[list[str]] = _dedupe(
    [
        "Regarde à droite.",
        "Tourne la tête à droite.",
        "Oriente-toi à droite.",
        "À droite Richie.",
        "Tourne à droite.",
        "Regarde vers la droite.",
        "Bouge la tête à droite.",
        "Le regard à droite.",
        "Va à droite avec la tête.",
        "Tourne ton regard à droite.",
        "Regarde côté droit.",
        "Tourne-toi vers la droite.",
        "Oriente ton regard à droite.",
        "Tête à droite.",
        "Mets ta tête à droite.",
        "Regarde du côté droit.",
        "Tourne la tête vers la droite.",
        "Fixe à droite.",
        "Regarde à droite stp.",
        "Hey à droite.",
        "Regarde à droite qui c'est.",
        "Regarde vers le côté droit.",
        "Tourne à droite la tête.",
        "Dirige ton regard à droite.",
        "À droite avec la tête.",
        "Déplace ta tête à droite.",
        "Tourne la tête du côté droit.",
        "Droite avec la tête.",
        "Oriente-toi vers la droite.",
        "Regarde le côté droit.",
        "Tête vers la droite.",
        "Tourne vers la droite.",
        "Regarde à droite maintenant.",
        "Tourne la tête sur la droite.",
        "Dirige-toi à droite.",
        "À droite avec ton regard.",
        "Pose ton regard à droite.",
        "Tourne à droite s'il te plaît.",
        "Regarde à droite là.",
        "Regarde à droite vite.",
        "Montre la droite.",
    ]
)

_MOVE_UP: Final[list[str]] = _dedupe(
    [
        "Regarde en haut.",
        "Tourne la tête vers le haut.",
        "Oriente-toi vers le haut.",
        "Lève les yeux.",
        "Lève la tête.",
        "Regarde vers le haut.",
        "Bouge la tête vers le haut.",
        "Le regard en haut.",
        "Va vers le haut avec la tête.",
        "Tourne ton regard vers le haut.",
        "Regarde au-dessus.",
        "Tourne-toi vers le haut.",
        "Oriente ton regard vers le haut.",
        "Tête en haut.",
        "Mets ta tête en haut.",
        "Regarde vers le plafond.",
        "Tourne la tête vers le haut.",
        "Fixe en haut.",
        "Regarde en haut stp.",
        "Hey en haut.",
        "Regarde en haut qui c'est.",
        "Regarde vers le ciel.",
        "Tourne en haut la tête.",
        "Dirige ton regard vers le haut.",
        "En haut avec la tête.",
        "Déplace ta tête vers le haut.",
        "Tourne la tête vers le haut.",
        "Haut avec la tête.",
        "Oriente-toi vers le haut.",
        "Regarde le haut.",
        "Tête vers le haut.",
        "Tourne vers le haut.",
        "Regarde en haut maintenant.",
        "Tourne la tête sur le haut.",
        "Dirige-toi vers le haut.",
        "En haut avec ton regard.",
        "Pose ton regard en haut.",
        "Lève ton regard.",
        "Regarde en haut s'il te plaît.",
        "Regarde en haut là.",
    ]
)

_MOVE_DOWN: Final[list[str]] = _dedupe(
    [
        "Regarde en bas.",
        "Tourne la tête vers le bas.",
        "Oriente-toi vers le bas.",
        "Baisse les yeux.",
        "Baisse la tête.",
        "Regarde vers le bas.",
        "Bouge la tête vers le bas.",
        "Le regard en bas.",
        "Va vers le bas avec la tête.",
        "Tourne ton regard vers le bas.",
        "Regarde en dessous.",
        "Tourne-toi vers le bas.",
        "Oriente ton regard vers le bas.",
        "Tête en bas.",
        "Mets ta tête en bas.",
        "Regarde vers le sol.",
        "Tourne la tête vers le bas.",
        "Fixe en bas.",
        "Regarde en bas stp.",
        "Hey en bas.",
        "Regarde en bas ce qu'il y a.",
        "Regarde vers le sol.",
        "Tourne en bas la tête.",
        "Dirige ton regard vers le bas.",
        "En bas avec la tête.",
        "Déplace ta tête vers le bas.",
        "Tourne la tête vers le bas.",
        "Bas avec la tête.",
        "Oriente-toi vers le bas.",
        "Regarde le bas.",
        "Tête vers le bas.",
        "Tourne vers le bas.",
        "Regarde en bas maintenant.",
        "Tourne la tête sur le bas.",
        "Dirige-toi vers le bas.",
        "En bas avec ton regard.",
        "Pose ton regard en bas.",
        "Baisse ton regard.",
        "Regarde en bas s'il te plaît.",
        "Regarde en bas là.",
    ]
)

_MOVE_FRONT: Final[list[str]] = _dedupe(
    [
        "Regarde devant toi.",
        "Tourne la tête vers l'avant.",
        "Oriente-toi vers l'avant.",
        "Regarde droit devant.",
        "Regarde en face.",
        "Regarde vers l'avant.",
        "Bouge la tête vers l'avant.",
        "Le regard devant.",
        "Va vers l'avant avec la tête.",
        "Tourne ton regard vers l'avant.",
        "Regarde face à toi.",
        "Tourne-toi vers l'avant.",
        "Oriente ton regard vers l'avant.",
        "Tête vers l'avant.",
        "Mets ta tête droit.",
        "Regarde tout droit.",
        "Tourne la tête vers l'avant.",
        "Fixe devant.",
        "Regarde devant stp.",
        "Hey devant.",
        "Regarde devant toi maintenant.",
        "Regarde vers le devant.",
        "Tourne vers l'avant la tête.",
        "Dirige ton regard vers l'avant.",
        "Devant avec la tête.",
        "Déplace ta tête vers l'avant.",
        "Tourne la tête vers le devant.",
        "Avant avec la tête.",
        "Oriente-toi vers le devant.",
        "Regarde le devant.",
        "Tête vers le devant.",
        "Tourne vers le devant.",
        "Regarde devant maintenant.",
        "Tourne la tête sur le devant.",
        "Dirige-toi vers l'avant.",
        "Devant avec ton regard.",
        "Pose ton regard devant.",
        "Regarde en face de toi.",
        "Regarde devant s'il te plaît.",
        "Regarde devant là.",
    ]
)

# --- Emotions (30–40 variants; semantics per EMOTIONS_REFERENCE) ---------------

_EMOTION_PHRASES: Final[dict[str, list[str]]] = {
    "sad": _dedupe(
        [
            "Fais le triste.",
            "Fait le triste.",
            "Montre que t'es triste.",
            "Joue la tristesse.",
            "Fais la tristesse.",
            "Pleure.",
            "Fais semblant de pleurer.",
            "Montre-moi que tu es triste.",
            "Tu peux faire le triste?",
            "Affiche la tristesse.",
            "Fais une mine triste.",
            "Montre ton côté triste.",
            "Sois triste.",
            "Fais le triste Richie.",
            "Montre la tristesse.",
            "Fais le personnage triste.",
            "Joue un personnage triste.",
            "Fais le déprimé.",
            "Montre que tu es déçu.",
            "Fais le déçu.",
            "Montre ta peine.",
            "Fais la peine.",
            "Fais le chagrin.",
            "Montre le chagrin.",
            "Fais le malheureux.",
            "Montre que tu es malheureux.",
            "Fais le morose.",
            "Montre une mine abattue.",
            "Fais l'air triste.",
            "Montre que tu es au fond.",
            "Fais le triste maintenant.",
            "Montre-moi la tristesse.",
            "Fais le triste stp.",
            "Joue triste.",
            "Fais triste.",
            "Montre triste.",
            "Fais le triste pour moi.",
            "Montre que t'es déçu.",
            "Fais le déçu maintenant.",
            "Honnêtement je te déteste.",
        ]
    ),
    "happy": _dedupe(
        [
            "Fais le beau.",
            "Fais le joyeux.",
            "Montre que t'es content.",
            "Fais le content.",
            "Fais-moi ton plus beau sourire.",
            "Montre-moi comment tu fais le beau.",
            "Fais le rire.",
            "Montre ta joie.",
            "Fais la joie.",
            "Sois joyeux.",
            "Fais le heureux.",
            "Montre que tu es heureux.",
            "Fais le sourire.",
            "Montre un sourire.",
            "Fais le positif.",
            "Montre ton bonheur.",
            "Fais le bonheur.",
            "C'est hyper marrant.",
            "Fais le marrant.",
            "Montre que tu es content.",
            "Tu peux faire le beau?",
            "Fais le beau Richie.",
            "Montre le beau.",
            "Fais le joyeux maintenant.",
            "Montre la joie.",
            "Fais joyeux.",
            "Montre joyeux.",
            "Fais le content maintenant.",
            "Montre-moi le beau.",
            "Fais le sourire maintenant.",
            "Montre un grand sourire.",
            "Fais le radieux.",
            "Montre que t'es radieux.",
            "Fais le gai.",
            "Montre que tu es gai.",
            "Fais le bon garçon.",
            "Montre que tu es de bonne humeur.",
            "Fais la bonne humeur.",
            "Montre la bonne humeur.",
            "Fais le beau stp.",
        ]
    ),
    "loving": _dedupe(
        [
            "Fais l'amoureux.",
            "Montre que tu m'aimes.",
            "Fais le tendre.",
            "Montre la tendresse.",
            "Fais le câlin.",
            "Fais-moi un bisou.",
            "Fais un bisou.",
            "Montre ton affection.",
            "Fais l'affectueux.",
            "Tu es beau mon Richy.",
            "T'as de beaux yeux, tu sais.",
            "Tu as de beaux yeux, tu sais.",
            "Tu sais que t'es un petit robot trop mignon?",
            "Regarde ce fin cœur.",
            "Je t'aime, Richie, tu le sais ça?",
            "C'est vrai que tu es tout mignon.",
            "Montre que tu m'aimes bien.",
            "Fais le mignon.",
            "Montre le mignon.",
            "Fais le doux.",
            "Montre le doux.",
            "Fais le cœur.",
            "Montre le cœur.",
            "Fais le loving.",
            "Montre l'amour.",
            "Fais l'amour.",
            "Montre que tu es adorable.",
            "Fais l'adorable.",
            "Allez Richie, arrête de faire le timide et fais-moi un bisou.",
            "Qu'est-ce que je serais sans toi?",
            "Qu'est-ce que je ferais sans toi?",
            "Montre que tu es tendre.",
            "Fais tendre.",
            "Montre tendre.",
            "Fais le bisou.",
            "Montre le bisou.",
            "Fais le petit cœur.",
            "Montre le petit cœur.",
            "Fais le romantique.",
            "Montre le romantique.",
        ]
    ),
    "scared": _dedupe(
        [
            "Fais la peur.",
            "Fait la peur.",
            "Montre que t'as peur.",
            "Fais le effrayé.",
            "Fais le peur.",
            "Montre la peur.",
            "Joue la peur.",
            "Fais le scared.",
            "Montre que tu as peur.",
            "Sois effrayé.",
            "Fais l'effrayé.",
            "Montre l'effrayé.",
            "Fais le terrorisé.",
            "Montre le terrorisé.",
            "Fais le paniqué.",
            "Montre le paniqué.",
            "Fais le apeuré.",
            "Montre l'apeuré.",
            "Tu sais que là, mon chef il est venu me voir et j'ai cru qu'il allait me virer.",
            "J'ai adopté un gros chien et il va te manger.",
            "Fais la peur maintenant.",
            "Montre la peur maintenant.",
            "Fais peur.",
            "Montre peur.",
            "Fais le peureux.",
            "Montre le peureux.",
            "Fais le trouillard.",
            "Montre le trouillard.",
            "Fais le sursaut.",
            "Montre le sursaut.",
            "Fais le sursauté.",
            "Montre le sursauté.",
            "Fais le horrifié.",
            "Montre le horrifié.",
            "Fais le effroi.",
            "Montre l'effroi.",
            "Fais l'effroi.",
            "Montre que tu es horrifié.",
            "Fais le horrifié maintenant.",
        ]
    ),
    "angry": _dedupe(
        [
            "Fais la colère.",
            "Fais le furieux.",
            "Montre ta colère.",
            "Fais le enragé.",
            "Montre la rage.",
            "Fais la rage.",
            "Sois en colère.",
            "Montre que tu es en colère.",
            "Fais le colérique.",
            "Montre le colérique.",
            "Fais le furax.",
            "Montre le furax.",
            "Fais le rageur.",
            "Montre le rageur.",
            "Fais le courroucé.",
            "Montre le courroucé.",
            "Fais le courroux.",
            "Montre le courroux.",
            "Fais le violent.",
            "Montre le violent.",
            "Fais le énervé fort.",
            "Montre que tu es furieux.",
            "Fais le furieux maintenant.",
            "Montre la colère maintenant.",
            "Fais colère.",
            "Montre colère.",
            "Fais le angry.",
            "Montre angry.",
            "Fais le furibond.",
            "Montre le furibond.",
            "Fais le exaspéré.",
            "Montre l'exaspéré.",
            "Fais le outré.",
            "Montre l'outré.",
            "Fais le indigné.",
            "Montre l'indigné.",
            "Fais le indignation.",
            "Montre l'indignation.",
            "Fais le rage.",
            "Montre rage.",
        ]
    ),
    "surprised": _dedupe(
        [
            "Fais la surprise.",
            "Montre que tu es surpris.",
            "Fais le surpris.",
            "Montre la surprise.",
            "Sois surpris.",
            "Fais le étonné.",
            "Montre l'étonné.",
            "Fais l'étonnement.",
            "Montre l'étonnement.",
            "Oh, il se met à pleuvoir!",
            "T'es pas au courant de la nouvelle d'aujourd'hui?",
            "T'es pas au courant de la nouvelle?",
            "Boo! Je t'ai fait peur?",
            "Fais le choqué.",
            "Montre le choqué.",
            "Fais le sidéré.",
            "Montre le sidéré.",
            "Fais le stupéfait.",
            "Montre le stupéfait.",
            "Fais le ah.",
            "Montre le ah.",
            "Fais le wow.",
            "Montre le wow.",
            "Fais la surprise maintenant.",
            "Montre la surprise maintenant.",
            "Fais surpris.",
            "Montre surpris.",
            "Fais le surprised.",
            "Montre surprised.",
            "Fais le ah bon.",
            "Montre ah bon.",
            "Fais le oh.",
            "Montre oh.",
            "Fais le oh là là.",
            "Montre oh là là.",
            "Fais le ah ouais.",
            "Montre ah ouais.",
            "Fais le incroyable.",
            "Montre l'incroyable.",
            "Fais l'incroyable.",
            "Montre que t'es choqué.",
        ]
    ),
    "excited": _dedupe(
        [
            "Fais l'excité.",
            "Montre ton enthousiasme.",
            "Fais l'enthousiaste.",
            "Montre l'enthousiasme.",
            "Fais le surexcité.",
            "Montre le surexcité.",
            "Tiens, regarde Richie, c'est ma petite cousine.",
            "Tu veux que je te présente Archie?",
            "Tu voudrais que je te présente Archie?",
            "Tu veux que je te présente ma famille?",
            "Fais le hype.",
            "Montre le hype.",
            "Fais le buzz.",
            "Montre le buzz.",
            "Fais le électrique.",
            "Montre l'électrique.",
            "Fais le dynamique.",
            "Montre le dynamique.",
            "Fais le énergique.",
            "Montre l'énergique.",
            "Fais le excité maintenant.",
            "Montre l'excitation.",
            "Fais l'excitation.",
            "Fais excité.",
            "Montre excité.",
            "Fais le excité Richie.",
            "Montre que tu es excité.",
            "Fais le super content.",
            "Montre le super content.",
            "Fais le surenthousiaste.",
            "Montre le surenthousiaste.",
            "Fais le émerveillé positif.",
            "Montre l'émerveillé positif.",
            "Fais le yeah.",
            "Montre yeah.",
            "Fais le ouais.",
            "Montre ouais.",
            "Fais le let's go.",
            "Montre let's go.",
            "Fais le hype maintenant.",
            "Montre hype.",
        ]
    ),
    "attentive": _dedupe(
        [
            "Sois attentif.",
            "Fais l'attentif.",
            "Montre que tu écoutes.",
            "Écoute-moi attentivement.",
            "Richie, j'ai un truc à te dire.",
            "J'ai un truc à te raconter.",
            "Allez Richie, on se concentre et on y retourne.",
            "J'aimerais que tu me fasses une recherche sur...",
            "Fais l'écoute.",
            "Montre l'écoute.",
            "Fais le concentré.",
            "Montre le concentré.",
            "Fais le focus.",
            "Montre le focus.",
            "Fais attention à moi.",
            "Montre ton attention.",
            "Fais l'attention.",
            "Montre l'attention.",
            "Fais le attentif maintenant.",
            "Montre attentif.",
            "Fais attentif.",
            "Fais le à l'écoute.",
            "Montre à l'écoute.",
            "Fais le alerte.",
            "Montre l'alerte.",
            "Fais l'alerte.",
            "Montre que tu es à l'écoute.",
            "Fais le vigilant.",
            "Montre le vigilant.",
            "Fais vigilant.",
            "Montre vigilant.",
            "Fais le recueillement.",
            "Montre le recueillement.",
            "Fais le recueilli.",
            "Montre le recueilli.",
            "Fais le prêt à écouter.",
            "Montre prêt à écouter.",
            "Fais le je t'écoute.",
            "Montre je t'écoute.",
            "Fais le écoute.",
            "Montre écoute.",
        ]
    ),
    "irritated": _dedupe(
        [
            "Fais l'agacé.",
            "Montre que t'es énervé.",
            "Fais l'énervé.",
            "Montre l'agacement.",
            "Fais l'agacement.",
            "J'ai marron.",
            "J'en ai profondément marre de toi.",
            "Je le supporte plus, il m'énerve!",
            "Tu es insupportable.",
            "Fais le nerveux.",
            "Montre le nerveux.",
            "Fais le exaspéré léger.",
            "Montre l'exaspéré léger.",
            "Fais le agacé maintenant.",
            "Montre agacé.",
            "Fais agacé.",
            "Fais le irrité.",
            "Montre irrité.",
            "Fais irrité.",
            "Fais le bougon.",
            "Montre le bougon.",
            "Fais le ronchon.",
            "Montre le ronchon.",
            "Fais le grincheux.",
            "Montre le grincheux.",
            "Fais le agacé Richie.",
            "Montre que tu es agacé.",
            "Fais le énervé léger.",
            "Montre énervé léger.",
            "Fais le marre.",
            "Montre marre.",
            "Fais le ras le bol.",
            "Montre ras le bol.",
            "Fais le ça m'énerve.",
            "Montre ça m'énerve.",
            "Fais le agacement.",
            "Montre agacement.",
            "Fais le impatient agacé.",
            "Montre impatient agacé.",
            "Fais le contrarié.",
            "Montre contrarié.",
        ]
    ),
    "disgusted": _dedupe(
        [
            "Fais le dégoût.",
            "Fait le dégoût.",
            "Fais le dégoûté.",
            "Montre le dégoût.",
            "Montre que tu es dégoûté.",
            "Fais la grimace de dégoût.",
            "Montre la grimace de dégoût.",
            "Regarde le fond de mon café, ça a l'air dégoûtant.",
            "Ça sent bizarre dehors, j'ai envie de vomir.",
            "Fais le écœuré.",
            "Montre l'écœuré.",
            "Fais l'écœuré.",
            "Montre écœuré.",
            "Fais écœuré.",
            "Fais le dégoût maintenant.",
            "Montre dégoût.",
            "Fais dégoût.",
            "Fais le dégouté.",
            "Montre dégouté.",
            "Fais le nausée.",
            "Montre nausée.",
            "Fais nausée.",
            "Montre que t'es dégoûté.",
            "Fais le répugnant.",
            "Montre répugnant.",
            "Fais répugnant.",
            "Fais le beurk.",
            "Montre beurk.",
            "Fais beurk.",
            "Fais le pouah.",
            "Montre pouah.",
            "Fais pouah.",
            "Fais le grimace.",
            "Montre grimace.",
            "Fais grimace.",
            "Fais le dégoûté Richie.",
            "Montre dégoûté Richie.",
            "Fais le dégoût pour moi.",
            "Montre dégoût pour moi.",
            "Fais le dégoût stp.",
            "Montre dégoût stp.",
        ]
    ),
    "displeased": _dedupe(
        [
            "Fais le mécontent.",
            "Montre ton déplaisir.",
            "Fais le déplaisir.",
            "Montre le mécontent.",
            "T'es méchant.",
            "T'es tellement moche.",
            "Fais le boudeur.",
            "Montre le boudeur.",
            "Fais le renfrogné.",
            "Montre le renfrogné.",
            "Fais le maussade.",
            "Montre le maussade.",
            "Fais le pas content.",
            "Montre pas content.",
            "Fais pas content.",
            "Montre que tu es mécontent.",
            "Fais le fâché léger.",
            "Montre fâché léger.",
            "Fais fâché léger.",
            "Fais le désapprobateur.",
            "Montre désapprobateur.",
            "Fais désapprobateur.",
            "Fais le désapprobation.",
            "Montre désapprobation.",
            "Fais désapprobation.",
            "Fais le pas d'accord.",
            "Montre pas d'accord.",
            "Fais pas d'accord.",
            "Fais le mécontent maintenant.",
            "Montre mécontent.",
            "Fais mécontent.",
            "Fais le displeased.",
            "Montre displeased.",
            "Fais displeased.",
            "Fais le déçu mécontent.",
            "Montre déçu mécontent.",
            "Fais déçu mécontent.",
            "Fais le pas satisfait.",
            "Montre pas satisfait.",
            "Fais pas satisfait.",
        ]
    ),
    "thinking": _dedupe(
        [
            "Réfléchis.",
            "Fais le réfléchi.",
            "Montre que tu réfléchis.",
            "Tu peux m'aider à réfléchir?",
            "Alors là, c'est une question compliquée que je vais te poser.",
            "J'arrive un peu au bout de mes idées.",
            "Fais le penseur.",
            "Montre le penseur.",
            "Fais le pensif.",
            "Montre le pensif.",
            "Fais le cogitation.",
            "Montre cogitation.",
            "Fais cogitation.",
            "Fais le hmm.",
            "Montre hmm.",
            "Fais hmm.",
            "Fais le réflexion.",
            "Montre réflexion.",
            "Fais réflexion.",
            "Fais le thoughtful.",
            "Montre thoughtful.",
            "Fais thoughtful.",
            "Fais le réfléchis maintenant.",
            "Montre réfléchis.",
            "Fais réfléchis.",
            "Fais le je réfléchis.",
            "Montre je réfléchis.",
            "Fais je réfléchis.",
            "Fais le analyse.",
            "Montre analyse.",
            "Fais analyse.",
            "Fais le calcul.",
            "Montre calcul.",
            "Fais calcul.",
            "Fais le réfléchi Richie.",
            "Montre réfléchi Richie.",
            "Fais le réfléchi stp.",
            "Montre réfléchi stp.",
            "Fais le réfléchi pour moi.",
            "Montre réfléchi pour moi.",
        ]
    ),
    "success": _dedupe(
        [
            "Fais le succès.",
            "Montre la réussite.",
            "Fais la réussite.",
            "Tu sais aujourd'hui j'ai accompli beaucoup de choses.",
            "Et c'est comme ça que j'ai réussi mon projet.",
            "Fais le bravo.",
            "Montre bravo.",
            "Fais bravo.",
            "Fais le victoire.",
            "Montre victoire.",
            "Fais victoire.",
            "Fais le gagnant.",
            "Montre gagnant.",
            "Fais gagnant.",
            "Fais le champion.",
            "Montre champion.",
            "Fais champion.",
            "Fais le yes.",
            "Montre yes.",
            "Fais yes.",
            "Fais le fierté.",
            "Montre fierté.",
            "Fais fierté.",
            "Fais le satisfait.",
            "Montre satisfait.",
            "Fais satisfait.",
            "Fais le accompli.",
            "Montre accompli.",
            "Fais accompli.",
            "Fais le réussi.",
            "Montre réussi.",
            "Fais réussi.",
            "Fais le success.",
            "Montre success.",
            "Fais success.",
            "Fais le succès maintenant.",
            "Montre succès.",
            "Fais succès.",
            "Fais le succès Richie.",
            "Montre succès Richie.",
        ]
    ),
    "greeting": _dedupe(
        [
            "Fais un coucou.",
            "Tu fais un coucou à mes collègues?",
            "Je vous présente Coralie.",
            "Fais le salut.",
            "Montre le salut.",
            "Fais salut.",
            "Montre salut.",
            "Fais le bonjour.",
            "Montre bonjour.",
            "Fais bonjour.",
            "Fais le hello.",
            "Montre hello.",
            "Fais hello.",
            "Fais le coucou.",
            "Montre coucou.",
            "Fais coucou.",
            "Fais le greeting.",
            "Montre greeting.",
            "Fais greeting.",
            "Fais le salutation.",
            "Montre salutation.",
            "Fais salutation.",
            "Fais le salut court.",
            "Montre salut court.",
            "Fais salut court.",
            "Fais le hey.",
            "Montre hey.",
            "Fais hey.",
            "Fais le yo.",
            "Montre yo.",
            "Fais yo.",
            "Fais le coucou maintenant.",
            "Montre coucou maintenant.",
            "Fais coucou maintenant.",
            "Fais le salut Richie.",
            "Montre salut Richie.",
            "Fais salut Richie.",
            "Fais le coucou aux collègues.",
            "Montre coucou aux collègues.",
        ]
    ),
    "welcoming": _dedupe(
        [
            "Fais l'accueil.",
            "Montre l'accueil.",
            "Fais le accueillant.",
            "Montre accueillant.",
            "Fais accueillant.",
            "Je te présente Pierre.",
            "Je te présente Paul.",
            "Fais le welcoming.",
            "Montre welcoming.",
            "Fais welcoming.",
            "Fais le bienvenue.",
            "Montre bienvenue.",
            "Fais bienvenue.",
            "Fais le chaleureux.",
            "Montre chaleureux.",
            "Fais chaleureux.",
            "Fais le accueil chaleureux.",
            "Montre accueil chaleureux.",
            "Fais accueil chaleureux.",
            "Fais le invite.",
            "Montre invite.",
            "Fais invite.",
            "Fais le ouvre les bras.",
            "Montre ouvre les bras.",
            "Fais ouvre les bras.",
            "Fais le accueille.",
            "Montre accueille.",
            "Fais accueille.",
            "Fais le accueille les invités.",
            "Montre accueille les invités.",
            "Fais accueille les invités.",
            "Fais le welcoming maintenant.",
            "Montre welcoming maintenant.",
            "Fais welcoming maintenant.",
            "Fais le welcoming Richie.",
            "Montre welcoming Richie.",
            "Fais welcoming Richie.",
            "Fais le accueil maintenant.",
            "Montre accueil maintenant.",
            "Fais accueil maintenant.",
        ]
    ),
    "calming": _dedupe(
        [
            "Fais le zen.",
            "Montre le zen.",
            "Fais zen.",
            "Montre zen.",
            "Ok, on s'arrête et on fait zen.",
            "Arrête d'être impatient comme ça.",
            "Fais le calme.",
            "Montre le calme.",
            "Fais calme.",
            "Montre calme.",
            "Fais le apaisé.",
            "Montre apaisé.",
            "Fais apaisé.",
            "Fais le relaxing.",
            "Montre relaxing.",
            "Fais relaxing.",
            "Fais le calming.",
            "Montre calming.",
            "Fais calming.",
            "Fais le détendu.",
            "Montre détendu.",
            "Fais détendu.",
            "Fais le tranquille.",
            "Montre tranquille.",
            "Fais tranquille.",
            "Fais le serein.",
            "Montre serein.",
            "Fais serein.",
            "Fais le pacifié.",
            "Montre pacifié.",
            "Fais pacifié.",
            "Fais le zen maintenant.",
            "Montre zen maintenant.",
            "Fais zen maintenant.",
            "Fais le calme Richie.",
            "Montre calme Richie.",
            "Fais calme Richie.",
            "Fais le zen stp.",
            "Montre zen stp.",
            "Fais zen stp.",
        ]
    ),
    "impatient": _dedupe(
        [
            "Fais l'impatient.",
            "Montre l'impatience.",
            "Fais l'impatience.",
            "Il te tarde que je te présente de nouveaux copains?",
            "Tu es impatient de savoir la suite?",
            "Fais le pressé.",
            "Montre pressé.",
            "Fais pressé.",
            "Fais le vite.",
            "Montre vite.",
            "Fais vite.",
            "Fais le impatient maintenant.",
            "Montre impatient.",
            "Fais impatient.",
            "Fais le impatient Richie.",
            "Montre impatient Richie.",
            "Fais impatient Richie.",
            "Fais le tarde.",
            "Montre tarde.",
            "Fais tarde.",
            "Fais le dépêche.",
            "Montre dépêche.",
            "Fais dépêche.",
            "Fais le allez allez.",
            "Montre allez allez.",
            "Fais allez allez.",
            "Fais le bouge toi.",
            "Montre bouge toi.",
            "Fais bouge toi.",
            "Fais le impatient stp.",
            "Montre impatient stp.",
            "Fais impatient stp.",
            "Fais le impatient pour moi.",
            "Montre impatient pour moi.",
            "Fais impatient pour moi.",
            "Fais le impatient maintenant.",
            "Montre impatient maintenant.",
            "Fais impatient maintenant.",
            "Fais le impatient vite.",
            "Montre impatient vite.",
        ]
    ),
    "embarrassed": _dedupe(
        [
            "Fais le timide.",
            "Montre le timide.",
            "Fais timide.",
            "Montre timide.",
            "T'es timide?",
            "Ne sois pas timide comme ça.",
            "Fais le gêné.",
            "Montre gêné.",
            "Fais gêné.",
            "Fais le embarrassed.",
            "Montre embarrassed.",
            "Fais embarrassed.",
            "Fais le rougissant.",
            "Montre rougissant.",
            "Fais rougissant.",
            "Fais le shy.",
            "Montre shy.",
            "Fais shy.",
            "Fais le timide maintenant.",
            "Montre timide maintenant.",
            "Fais timide maintenant.",
            "Fais le timide Richie.",
            "Montre timide Richie.",
            "Fais timide Richie.",
            "Fais le gêné maintenant.",
            "Montre gêné maintenant.",
            "Fais gêné maintenant.",
            "Fais le timide stp.",
            "Montre timide stp.",
            "Fais timide stp.",
            "Fais le timide pour moi.",
            "Montre timide pour moi.",
            "Fais timide pour moi.",
            "Fais le rougit.",
            "Montre rougit.",
            "Fais rougit.",
            "Fais le mal à l'aise.",
            "Montre mal à l'aise.",
            "Fais mal à l'aise.",
            "Fais le timide là.",
            "Montre timide là.",
        ]
    ),
    "dying": _dedupe(
        [
            "Fais le mort.",
            "Fait le mort.",
            "C'est le mort.",
            "Fais le dying.",
            "Montre dying.",
            "Fais dying.",
            "Fais le à bout de souffle.",
            "Montre à bout de souffle.",
            "Fais à bout de souffle.",
            "Fais le KO.",
            "Montre KO.",
            "Fais KO.",
            "Fais le épuisé comique.",
            "Montre épuisé comique.",
            "Fais épuisé comique.",
            "Fais le panting.",
            "Montre panting.",
            "Fais panting.",
            "Fais le out of breath.",
            "Montre out of breath.",
            "Fais out of breath.",
            "Fais le mort comique.",
            "Montre mort comique.",
            "Fais mort comique.",
            "Fais le dying maintenant.",
            "Montre dying maintenant.",
            "Fais dying maintenant.",
            "Fais le mort Richie.",
            "Montre mort Richie.",
            "Fais mort Richie.",
            "Fais le mort stp.",
            "Montre mort stp.",
            "Fais mort stp.",
            "Fais le mort pour moi.",
            "Montre mort pour moi.",
            "Fais mort pour moi.",
            "Fais le dying stp.",
            "Montre dying stp.",
            "Fais dying stp.",
            "Fais le dying pour moi.",
            "Montre dying pour moi.",
        ]
    ),
    "tired": _dedupe(
        [
            "Fais le fatigué.",
            "Montre la fatigue.",
            "Fais la fatigue.",
            "Aujourd'hui, j'ai eu une longue journée avec mes collègues.",
            "Fais le épuisé.",
            "Montre épuisé.",
            "Fais épuisé.",
            "Fais le worn out.",
            "Montre worn out.",
            "Fais worn out.",
            "Fais le tired.",
            "Montre tired.",
            "Fais tired.",
            "Fais le fatigué maintenant.",
            "Montre fatigué.",
            "Fais fatigué.",
            "Fais le fatigué Richie.",
            "Montre fatigué Richie.",
            "Fais fatigué Richie.",
            "Fais le fatigué stp.",
            "Montre fatigué stp.",
            "Fais fatigué stp.",
            "Fais le fatigué pour moi.",
            "Montre fatigué pour moi.",
            "Fais fatigué pour moi.",
            "Fais le creuvé.",
            "Montre creuvé.",
            "Fais creuvé.",
            "Fais le à bout.",
            "Montre à bout.",
            "Fais à bout.",
            "Fais le lessivé.",
            "Montre lessivé.",
            "Fais lessivé.",
            "Fais le fatigue.",
            "Montre fatigue.",
            "Fais fatigue.",
            "Fais le longue journée.",
            "Montre longue journée.",
            "Fais longue journée.",
            "Fais le fatigué là.",
            "Montre fatigué là.",
        ]
    ),
    "sleepy": _dedupe(
        [
            "Fais le somnolent.",
            "Montre la somnolence.",
            "Fais la somnolence.",
            "Tu as envie de faire dodo?",
            "Fais le endormi.",
            "Montre endormi.",
            "Fais endormi.",
            "Fais le sleepy.",
            "Montre sleepy.",
            "Fais sleepy.",
            "Fais le dodo.",
            "Montre dodo.",
            "Fais dodo.",
            "Fais le bâille.",
            "Montre bâille.",
            "Fais bâille.",
            "Fais le sommeil.",
            "Montre sommeil.",
            "Fais sommeil.",
            "Fais le somnolent maintenant.",
            "Montre somnolent.",
            "Fais somnolent.",
            "Fais le somnolent Richie.",
            "Montre somnolent Richie.",
            "Fais somnolent Richie.",
            "Fais le somnolent stp.",
            "Montre somnolent stp.",
            "Fais somnolent stp.",
            "Fais le somnolent pour moi.",
            "Montre somnolent pour moi.",
            "Fais somnolent pour moi.",
            "Fais le endormi maintenant.",
            "Montre endormi maintenant.",
            "Fais endormi maintenant.",
            "Fais le dodo maintenant.",
            "Montre dodo maintenant.",
            "Fais dodo maintenant.",
            "Fais le somnolent là.",
            "Montre somnolent là.",
            "Fais somnolent là.",
        ]
    ),
    "goodbye": _dedupe(
        [
            "Fais l'au revoir.",
            "Montre l'au revoir.",
            "Fais au revoir.",
            "Montre au revoir.",
            "Fais de beaux rêves, je vais te débrancher.",
            "Fais le goodbye.",
            "Montre goodbye.",
            "Fais goodbye.",
            "Fais le adieu.",
            "Montre adieu.",
            "Fais adieu.",
            "Fais le bye.",
            "Montre bye.",
            "Fais bye.",
            "Fais le à plus.",
            "Montre à plus.",
            "Fais à plus.",
            "Fais le salut au revoir.",
            "Montre salut au revoir.",
            "Fais salut au revoir.",
            "Fais le départ.",
            "Montre départ.",
            "Fais départ.",
            "Fais le goodbye maintenant.",
            "Montre goodbye maintenant.",
            "Fais goodbye maintenant.",
            "Fais le goodbye Richie.",
            "Montre goodbye Richie.",
            "Fais goodbye Richie.",
            "Fais le goodbye stp.",
            "Montre goodbye stp.",
            "Fais goodbye stp.",
            "Fais le goodbye pour moi.",
            "Montre goodbye pour moi.",
            "Fais goodbye pour moi.",
            "Fais le au revoir maintenant.",
            "Montre au revoir maintenant.",
            "Fais au revoir maintenant.",
            "Fais le au revoir là.",
            "Montre au revoir là.",
        ]
    ),
    "anxious": _dedupe(
        [
            "Fais l'anxieux.",
            "Montre l'anxiété.",
            "Fais l'anxiété.",
            "Toi aussi t'as eu peur, non?",
            "Fais le stressé.",
            "Montre stressé.",
            "Fais stressé.",
            "Fais le anxieux.",
            "Montre anxieux.",
            "Fais anxieux.",
            "Fais le inquiet.",
            "Montre inquiet.",
            "Fais inquiet.",
            "Fais le nerveux stress.",
            "Montre nerveux stress.",
            "Fais nerveux stress.",
            "Fais le anxieux maintenant.",
            "Montre anxieux maintenant.",
            "Fais anxieux maintenant.",
            "Fais le anxieux Richie.",
            "Montre anxieux Richie.",
            "Fais anxieux Richie.",
            "Fais le anxieux stp.",
            "Montre anxieux stp.",
            "Fais anxieux stp.",
            "Fais le anxieux pour moi.",
            "Montre anxieux pour moi.",
            "Fais anxieux pour moi.",
            "Fais le stress.",
            "Montre stress.",
            "Fais stress.",
            "Fais le panique légère.",
            "Montre panique légère.",
            "Fais panique légère.",
            "Fais le angoissé.",
            "Montre angoissé.",
            "Fais angoissé.",
            "Fais le anxieux là.",
            "Montre anxieux là.",
            "Fais anxieux là.",
        ]
    ),
    "uncertain": _dedupe(
        [
            "Fais l'incertain.",
            "Montre l'incertitude.",
            "Fais l'incertitude.",
            "Tu es sûr de ce que tu dis?",
            "Fais le hésitant.",
            "Montre hésitant.",
            "Fais hésitant.",
            "Fais le uncertain.",
            "Montre uncertain.",
            "Fais uncertain.",
            "Fais le pas sûr.",
            "Montre pas sûr.",
            "Fais pas sûr.",
            "Fais le doute.",
            "Montre doute.",
            "Fais doute.",
            "Fais le incertain maintenant.",
            "Montre incertain.",
            "Fais incertain.",
            "Fais le incertain Richie.",
            "Montre incertain Richie.",
            "Fais incertain Richie.",
            "Fais le incertain stp.",
            "Montre incertain stp.",
            "Fais incertain stp.",
            "Fais le incertain pour moi.",
            "Montre incertain pour moi.",
            "Fais incertain pour moi.",
            "Fais le hmm pas sûr.",
            "Montre hmm pas sûr.",
            "Fais hmm pas sûr.",
            "Fais le euh.",
            "Montre euh.",
            "Fais euh.",
            "Fais le peut-être.",
            "Montre peut-être.",
            "Fais peut-être.",
            "Fais le incertain là.",
            "Montre incertain là.",
            "Fais incertain là.",
        ]
    ),
    "confused": _dedupe(
        [
            "Fais le confus.",
            "Montre la confusion.",
            "Fais la confusion.",
            "Non non, je pense que tu te trompes.",
            "Fais le perplexe.",
            "Montre perplexe.",
            "Fais perplexe.",
            "Fais le confused.",
            "Montre confused.",
            "Fais confused.",
            "Fais le perdu.",
            "Montre perdu.",
            "Fais perdu.",
            "Fais le désorienté.",
            "Montre désorienté.",
            "Fais désorienté.",
            "Fais le confus maintenant.",
            "Montre confus.",
            "Fais confus.",
            "Fais le confus Richie.",
            "Montre confus Richie.",
            "Fais confus Richie.",
            "Fais le confus stp.",
            "Montre confus stp.",
            "Fais confus stp.",
            "Fais le confus pour moi.",
            "Montre confus pour moi.",
            "Fais confus pour moi.",
            "Fais le hein.",
            "Montre hein.",
            "Fais hein.",
            "Fais le quoi.",
            "Montre quoi.",
            "Fais quoi.",
            "Fais le je comprends pas.",
            "Montre je comprends pas.",
            "Fais je comprends pas.",
            "Fais le confus là.",
            "Montre confus là.",
            "Fais confus là.",
        ]
    ),
}

PARAPHRASES: Final[dict[str, list[str]]] = {
    "head_tracking:on": _HEAD_ON,
    "head_tracking:off": _HEAD_OFF,
    "stop": _STOP,
    "dance": _DANCE,
    "move_head:left": _MOVE_LEFT,
    "move_head:right": _MOVE_RIGHT,
    "move_head:up": _MOVE_UP,
    "move_head:down": _MOVE_DOWN,
    "move_head:front": _MOVE_FRONT,
    **{_emotion(intent): phrases for intent, phrases in _EMOTION_PHRASES.items()},
}

# --- Chat traps (≥5 per command family; target 250+) ----------------------------

CHAT_TRAPS: Final[list[str]] = _dedupe(
    [
        # head_tracking traps
        "Pourquoi tu me regardes?",
        "C'est quoi le head tracking?",
        "Regarde la photo à gauche.",
        "Regarde ce qu'il y a sur la table.",
        "Tu peux me décrire ce que tu vois?",
        "Qu'est-ce que tu vois devant toi?",
        "Est-ce que tu me vois bien?",
        "Tu me regardes depuis tout à l'heure, c'est bizarre.",
        "Arrête de parler et dis-moi ce que tu vois.",
        "Le suivi du regard c'est quoi exactement?",
        "Tu suis les gens comment?",
        "Regarde le fond de la pièce et dis-moi.",
        "Quand tu me regardes tu vois quoi?",
        "Je t'ai demandé de regarder la fenêtre, pas moi.",
        "Regarde le tableau au mur.",
        "Tu peux analyser l'image?",
        "Montre-moi ce que la caméra voit.",
        "Tu n'es pas posé sur moi, Richie.",
        "Quand je te vois Richie, parfois j'ai l'impression de voir un petit garçon.",
        # move_head traps
        "À gauche de la table il y a quoi?",
        "Je voulais dire regarde à droite.",
        "À droite de la photo il y a quoi?",
        "Le chat est à gauche du canapé.",
        "Mets le vase à gauche.",
        "Tourne à gauche dans le couloir.",
        "La sortie est à droite.",
        "Regarde à gauche et à droite avant de traverser.",
        "Sur la photo de gauche on voit quoi?",
        "À gauche c'est plus joli non?",
        "Je préfère la version de droite.",
        "En haut à gauche de l'écran.",
        "En bas à droite il y a une tache.",
        "Tourne à gauche au prochain carrefour.",
        "La bibliothèque est à droite.",
        # dance traps
        "Tu danses bien en général?",
        "Pourquoi les gens dansent?",
        "Tu connais des chorégraphies célèbres?",
        "La danse c'est un art intéressant.",
        "Tu aimes quel style de danse?",
        "Attends, je vais te faire écouter une musique.",
        "Tu reconnais cette musique?",
        "Parce qu'en réalité, je te vois bouger mais je ne t'entends pas.",
        "On en est à soixante, il faudrait que j'en fasse beaucoup plus.",
        "Tu danses souvent?",
        "C'est quoi ta danse préférée?",
        "Les robots peuvent danser?",
        "J'adore danser le samedi soir.",
        "Ma sœur prend des cours de danse.",
        "La musique me donne envie de bouger.",
        # stop traps
        "Stop ou encore, tu connais?",
        "On arrête là pour aujourd'hui.",
        "J'ai passé des heures à nettoyer.",
        "On s'approche des cents?",
        "On s'approche des 100!",
        "Arrête de parler de ça.",
        "Ça suffit de plaisanter.",
        "Stop aux rumeurs.",
        "On arrête le débat là.",
        "Je voulais dire stop à la musique du voisin.",
        "Stop la pluie s'il te plaît.",
        "Arrête de pleuvoir.",
        "Stop aux notifications.",
        "On arrête la réunion dans cinq minutes.",
        "Arrête de penser à ça.",
        # sad / displeased / irritated traps
        "Je déteste les lundis.",
        "Pourquoi tu es triste?",
        "C'est triste comme nouvelle.",
        "Je suis triste pour lui.",
        "Cette chanson est triste.",
        "Je déteste le café froid.",
        "Je te déteste un peu quand tu fais ça.",
        "Il m'énerve ce collègue.",
        "J'en ai marre de la pluie.",
        "J'en ai marre du métro.",
        "T'es méchant avec les chats.",
        "T'es tellement moche ce tableau.",
        "Tu es insupportable quand tu mens.",
        "C'est insupportable cette chaleur.",
        # loving traps
        "C'est vrai que tu es tout mignon.",
        "J'adore ce projet.",
        "Je t'aime bien ce restaurant.",
        "Tu aimes la pluie?",
        "Tu sais que au travail je parle tout le temps de toi?",
        "T'imagines si j'arrivais à faire de toi un véritable petit garçon?",
        "Tu es beau ce modèle de robot en vitrine.",
        "J'aime bien Richie la marque.",
        "Mon neveu s'appelle Richie.",
        "C'est mignon comme chat.",
        # scared / anxious traps
        "J'ai peur qu'il pleuve demain.",
        "J'ai peur de rater mon examen.",
        "Tu as peur des araignées?",
        "La peur du vide c'est bizarre.",
        "J'ai eu peur en voyant le film.",
        "Toi aussi t'as eu peur, non?",
        "Je stresse pour la réunion.",
        "J'ai un peu d'anxiété sociale.",
        "Le stress au travail augmente.",
        "J'ai adopté un chien mais il est gentil.",
        # dying traps
        "Avec la semaine que j'ai passée, je vais être mort vendredi.",
        "Je suis mort de rire hier.",
        "Ce projet me tue.",
        "Je meurs de faim.",
        "Mort de fatigue ce soir.",
        "C'est le mort cette blague.",
        "Il est mort dans le film.",
        "Je suis à bout mais pas littéralement.",
        # surprised traps
        "Je suis surpris par la nouvelle.",
        "Quelle surprise!",
        "Oh, il se met à pleuvoir dehors.",
        "T'es pas au courant de la nouvelle du bureau?",
        "Boo! Je t'ai fait peur hier soir.",
        "C'est surprenant comme résultat.",
        "Je n'en reviens pas.",
        "Incroyable cette histoire.",
        # meta / vision / ambiguous
        "Joue l'émotion.",
        "Ok, réfléchis.",
        "Tu sais que là, tout l'objectif de mon travail, c'est de te créer des émotions pour que tu paraisses plus réaliste?",
        "Tu peux m'aider à réfléchir sur mon projet?",
        "Réfléchis à ce problème mathématique.",
        "Qu'est-ce que tu parles!",
        "Tais-toi un peu.",
        "Tu es tout calme.",
        "Tu es tout calme aujourd'hui.",
        "Imagine demain t'es autonome.",
        "Si tu devais être un animal, tu serais lequel?",
        "Raconte-moi une blague.",
        "Raconte une blague.",
        "Comment tu vas?",
        "Bonjour.",
        "Bonjour Maurici.",
        "Je veux que tu parles anglais.",
        "Je veux que tu parles mais qu'en français.",
        "Aucun souci. Tu sais quel temps il fait dehors ou pas?",
        "T'as fait quoi de beau aujourd'hui?",
        "Tu veux savoir ce que je fais?",
        "En vrai je trouve ça extrêmement intéressant.",
        "Cet après-midi, j'ai une collègue à m'a donné un document mais s'était trompée.",
        "Promis, tu ne surchauffes pas?",
        "Ah je l'espère aussi, on va échanger tous les deux pendant quelques instants.",
        # success / tired / goodbye conversational
        "Et c'est comme ça que j'ai réussi mon projet.",
        "Tu sais aujourd'hui j'ai accompli beaucoup de choses.",
        "Aujourd'hui, j'ai eu une longue journée avec mes collègues.",
        "Fais de beaux rêves, je vais dormir.",
        "Je vais te débrancher plus tard.",
        "Bonne nuit Richie.",
        "Au revoir la réunion.",
        "On se dit à demain au bureau.",
        # greeting / welcoming meta
        "Je vous présente mon rapport.",
        "Je te présente l'idée.",
        "Bonjour à tous dans le chat.",
        "Salut la team.",
        "Bienvenue sur le site.",
        "Bienvenue en France.",
        # thinking / attentive meta
        "J'ai un truc à te raconter plus tard.",
        "Écoute, je t'explique après.",
        "Concentre-toi sur ton code.",
        "Il faut qu'on réfléchisse ensemble demain.",
        "Attends je réfléchis.",
        # embarrassed / impatient meta
        "Ne sois pas timide avec les inconnus.",
        "Arrête d'être impatient, le train arrive.",
        "Il est impatient ce client.",
        "Tu es timide en réunion?",
        # disgusted meta
        "Ça sent bizarre dehors.",
        "Regarde le fond de mon café.",
        "Ce plat a l'air dégoûtant.",
        "J'ai envie de vomir après ce trajet.",
        # happy meta
        "C'est hyper marrant cette vidéo.",
        "Montre-moi comment tu fais le beau sur la photo.",
        "Fais le beau pour la photo.",
        # extra small talk
        "Quel est le sens de la vie?",
        "Tu connais Paris?",
        "Raconte-moi ta journée.",
        "Qu'est-ce que je serais sans toi dans cette équipe?",
        "Qu'est-ce que je ferais sans mon café?",
        "Tu connais Archie le logiciel?",
        "Richie est en retard.",
        "Le projet Reachy avance bien.",
        "On parle de head tracking au bureau.",
        "La caméra du téléphone est floue.",
        "Décris-moi la pièce.",
        "Tu peux résumer ce document?",
        "Lis-moi cet article.",
        "Traduis cette phrase.",
        "Quelle heure est-il?",
        "Tu sais quel jour on est?",
        "C'est quoi ton modèle?",
        "Tu utilises quel LLM?",
        "Explique-moi la relativité.",
        "Pourquoi le ciel est bleu?",
        "Tu aimes les chats?",
        "Mon chat regarde par la fenêtre.",
        "Regarde comme il pleut.",
        "Il pleut donc je reste.",
        "Stop aux fake news.",
        "Arrête de scroll.",
        "Danse avec les étoiles c'est un film.",
        "À gauche du politique, à droite de l'économie.",
        "Tourne en rond dans ma tête.",
        "Regarde-moi cette vidéo sur YouTube.",
        "Suis-moi sur Instagram.",
        "Fixe une date pour la réunion.",
        "Garde un œil sur le four, pas sur moi.",
        "Pleure pas, c'est pas grave.",
        "Fais attention en traversant.",
        "Montre-moi ton écran.",
        "Montre la doc.",
        "Fais-moi un résumé.",
        "Fais comme tu veux.",
        "Fais gaffe à la marche.",
        "Fais le point sur le projet.",
        "Fais le ménage demain.",
        "Fais la cuisine ce soir.",
    ]
)

# Minimum counts enforced by tests
MIN_PARAPHRASES_PER_LABEL: Final[int] = 30
MIN_CHAT_TRAPS: Final[int] = 150
